"""First migration

Revision ID: 60c49dc15d2d
Revises: 
Create Date: 2022-12-18 21:32:17.545796

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "60c49dc15d2d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("series", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("create_data", sa.TIMESTAMP(), nullable=True),
        sa.Column("expire_date", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("not_active", "active", "expired", name="statuscardenum"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("series", "number"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "card_transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("transaction_amount", sa.FLOAT(), nullable=False),
        sa.Column("transaction_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("id_card", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["id_card"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_transactions")
    op.drop_table("cards")
    # ### end Alembic commands ###
