"""First migration

Revision ID: 7bcb50dfabdd
Revises: 
Create Date: 2023-01-18 20:10:16.936534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bcb50dfabdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expire_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('not_active', 'active', 'expired', name='statuscardenum'), nullable=True),
    sa.PrimaryKeyConstraint('series', 'number'),
    sa.UniqueConstraint('id')
    )
    op.create_table('card_transactions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_card', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_transactions')
    op.drop_table('cards')
    # ### end Alembic commands ###
